version: 2

run:
  timeout: 5m

linters:
  default: none
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 10
